### ISSUE TITLE
GoldenCrates not working on 1.16.5 Purpur 

### ISSUE THREAD

**Issue by antiGriefer** [nulli0n/GoldenCrates#42]
The plugin doesn't work on purpur, what can I do to fix this?
![image](https://user-images.githubusercontent.com/67378144/111306128-1b685b00-8658-11eb-832b-817ea2f8dd08.png)

**Comment by nulli0n** [comment]
use the latest version

**Comment by antiGriefer** [comment]
> use the latest version

Already am

**Comment by nulli0n** [comment]
no, it's not the latest version of golden crates

**Comment by nulli0n** [comment]
ok then console logs maybe

**Comment by antiGriefer** [comment]
>.... [13:48:53 INFO]: [GoldenCrates] Enabling GoldenCrates v3.11.0
>.... [13:48:53 WARN]: [GoldenCrates] ============== DISCLAIMER ==============
>.... [13:48:53 WARN]: [GoldenCrates] > You're running an unknown Spigot fork.
>.... [13:48:53 WARN]: [GoldenCrates] > This plugin is designed to work on Spigot (spigotmc.org) only!
>.... [13:48:53 WARN]: [GoldenCrates] > You won't get any support for any issues unless they persist on regular Spigot.
>.... [13:48:53 WARN]: [GoldenCrates] ========================================
>.... [13:48:53 INFO]: [GoldenCrates] Powered by: NexEngine
>.... [13:48:53 INFO]: [GoldenCrates] [Hook] HolographicDisplays: Success!
>.... [13:48:53 INFO]: [PlaceholderAPI] Successfully registered expansion: goldencrates
>.... [13:48:53 INFO]: [GoldenCrates] [Hook] PlaceholderAPI: Success!
>.... [13:48:53 ERROR]: Error occurred while enabling GoldenCrates v3.11.0 (Is it up to date?)
java.lang.NoClassDefFoundError: net/citizensnpcs/api/event/NPCClickEvent
at su.nightexpress.goldencrates.GoldenCrates.registerHooks(GoldenCrates.java:135) ~[?:?]

**Comment by nulli0n** [comment]
update or remove Citizens

**Comment by antiGriefer** [comment]
>.... [13:48:53 INFO]: [GoldenCrates] Enabling GoldenCrates v3.11.0
>.... [13:48:53 WARN]: [GoldenCrates] ============== DISCLAIMER ==============
>.... [13:48:53 WARN]: [GoldenCrates] > You're running an unknown Spigot fork.
>.... [13:48:53 WARN]: [GoldenCrates] > This plugin is designed to work on Spigot (spigotmc.org) only!
>.... [13:48:53 WARN]: [GoldenCrates] > You won't get any support for any issues unless they persist on regular Spigot.
>.... [13:48:53 WARN]: [GoldenCrates] ========================================
>.... [13:48:53 INFO]: [GoldenCrates] Powered by: NexEngine
>.... [13:48:53 INFO]: [GoldenCrates] [Hook] HolographicDisplays: Success!
>.... [13:48:53 INFO]: [PlaceholderAPI] Successfully registered expansion: goldencrates
>.... [13:48:53 INFO]: [GoldenCrates] [Hook] PlaceholderAPI: Success!
>.... [13:48:53 ERROR]: Error occurred while enabling GoldenCrates v3.11.0 (Is it up to date?)
java.lang.NoClassDefFoundError: net/citizensnpcs/api/event/NPCClickEvent
at su.nightexpress.goldencrates.GoldenCrates.registerHooks(GoldenCrates.java:135) ~[?:?]

**Comment by nulli0n** [comment]
read update notes
